name: union_shop
description: A Flutter web app clone of Union Shop with dynamic data and cart (Phase 2).
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  firebase_auth_mocks: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
